-- MySQL Script generated by MySQL Workbench
-- 01/21/15 15:40:11
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tienda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tienda` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `tienda` ;

-- -----------------------------------------------------
-- Table `tienda`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tienda`.`categoria` ;

CREATE TABLE IF NOT EXISTS `tienda`.`categoria` (
  `id_cat` INT NOT NULL AUTO_INCREMENT,
  `nombre_cat` VARCHAR(45) NULL,
  `descripcion_cat` TEXT NULL,
  `anuncio_cat` TEXT NULL,
  `visible` TINYINT(1) NULL,
  `cod_cat` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cat`),
  UNIQUE INDEX `cod_cat_UNIQUE` (`cod_cat` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tienda`.`productos` ;

CREATE TABLE IF NOT EXISTS `tienda`.`productos` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre_producto` VARCHAR(45) NULL,
  `precio_producto` DECIMAL(6,2) NULL,
  `descuento` DECIMAL(5,2) NULL,
  `imagen_producto` VARCHAR(256) NULL,
  `iva_producto` DECIMAL(5,2) NULL,
  `descripcion` TEXT NULL,
  `anuncio` TEXT NULL,
  `stock` INT NULL,
  `categoria_id_cat` INT NOT NULL,
  `visible` TINYINT(1) NULL,
  `cod_producto` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_producto`, `categoria_id_cat`),
  INDEX `fk_productos_categoria_idx` (`categoria_id_cat` ASC),
  UNIQUE INDEX `cod_producto_UNIQUE` (`cod_producto` ASC),
  CONSTRAINT `fk_productos_categoria`
    FOREIGN KEY (`categoria_id_cat`)
    REFERENCES `tienda`.`categoria` (`id_cat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda`.`provincias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tienda`.`provincias` ;

CREATE TABLE IF NOT EXISTS `tienda`.`provincias` (
  `id_provincia` INT NOT NULL,
  `nombre_provincia` VARCHAR(45) NULL,
  PRIMARY KEY (`id_provincia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tienda`.`usuario` ;

CREATE TABLE IF NOT EXISTS `tienda`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(80) NOT NULL,
  `contrasenia` CHAR(40) NULL,
  `email` VARCHAR(128) NULL,
  `nombre` VARCHAR(80) NULL,
  `apellidos` VARCHAR(80) NULL,
  `dni` CHAR(9) NULL,
  `direccion` VARCHAR(100) NULL,
  `cp` CHAR(5) NULL,
  `provincias_id_provincia` INT NOT NULL,
  `rol` ENUM('Administrador','Usuario') NULL,
  `activo` TINYINT(1) NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuario_provincias1_idx` (`provincias_id_provincia` ASC),
  UNIQUE INDEX `nombre_usuario_UNIQUE` (`nombre_usuario` ASC),
  CONSTRAINT `fk_usuario_provincias1`
    FOREIGN KEY (`provincias_id_provincia`)
    REFERENCES `tienda`.`provincias` (`id_provincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tienda`.`pedido` ;

CREATE TABLE IF NOT EXISTS `tienda`.`pedido` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `estado` ENUM('Procesado','Pendiente','Recibido','Devuelto') NULL,
  `cantidad` INT(11) NULL,
  `fecha_pedido` DATE NULL,
  `fecha_entrega` DATE NULL,
  `usuario_id_usuario` INT NOT NULL,
  `nombre` VARCHAR(80) NULL,
  `apellidos` VARCHAR(80) NULL,
  `dni` CHAR(9) NULL,
  `direccion` VARCHAR(100) NULL,
  `cp` CHAR(5) NULL,
  PRIMARY KEY (`id_pedido`, `usuario_id_usuario`),
  INDEX `fk_pedido_usuario1_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_pedido_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `tienda`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda`.`linea_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tienda`.`linea_pedido` ;

CREATE TABLE IF NOT EXISTS `tienda`.`linea_pedido` (
  `productos_id_producto` INT NOT NULL,
  `productos_categoria_id_cat` INT NOT NULL,
  `pedido_id_pedido` INT NOT NULL,
  `cantidad` VARCHAR(45) NULL,
  `precio` DECIMAL(6,2) NULL,
  PRIMARY KEY (`productos_id_producto`, `productos_categoria_id_cat`, `pedido_id_pedido`),
  INDEX `fk_productos_has_pedido_pedido1_idx` (`pedido_id_pedido` ASC),
  INDEX `fk_productos_has_pedido_productos1_idx` (`productos_id_producto` ASC, `productos_categoria_id_cat` ASC),
  CONSTRAINT `fk_productos_has_pedido_productos1`
    FOREIGN KEY (`productos_id_producto` , `productos_categoria_id_cat`)
    REFERENCES `tienda`.`productos` (`id_producto` , `categoria_id_cat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_has_pedido_pedido1`
    FOREIGN KEY (`pedido_id_pedido`)
    REFERENCES `tienda`.`pedido` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda`.`destacado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tienda`.`destacado` ;

CREATE TABLE IF NOT EXISTS `tienda`.`destacado` (
  `productos_id_producto` INT NOT NULL,
  `productos_categoria_id_cat` INT NOT NULL,
  PRIMARY KEY (`productos_id_producto`, `productos_categoria_id_cat`),
  INDEX `fk_destacado_productos1_idx` (`productos_id_producto` ASC, `productos_categoria_id_cat` ASC),
  CONSTRAINT `fk_destacado_productos1`
    FOREIGN KEY (`productos_id_producto` , `productos_categoria_id_cat`)
    REFERENCES `tienda`.`productos` (`id_producto` , `categoria_id_cat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
